### ISSUE TITLE
Install loop?

### ISSUE THREAD

**Issue by mysterybear** [grough/lilac-loop-vcv#14]
Hey

When I try to install this, it installs the files like so:

![image](https://user-images.githubusercontent.com/50906986/183283035-dcc7fed8-c495-4b77-af69-ecfb8fa822cc.png)

But it doesn't show in the plugin library in Rack, and it always shows like this:

![image](https://user-images.githubusercontent.com/50906986/183283050-102e5a10-ea61-415d-a305-b64ae5d321af.png)

I'm on Archlinux, Rack v2.1.2, any ideas? Never had this with other modules. I also tried installing it the way you have to install the stoermelder modules for Rack v2 (by downloading the `.vcvplugin` file from the release and putting it in plugins) but that didn't work either.

**Comment by grough** [comment]
I'm not sure what could be happening here. When I have problems with my Rack library, I make a backup of my user folder and start fresh to see if it makes a difference. The looper plugin isn't doing anything out of the ordinary that should cause problems in the library.

**Comment by mysterybear** [comment]
Thanks for reply @grough this issue has actually started happening with Fundamental modules also! Must be a VCV thing I think, I've raised it with their support and am waiting for them to follow-up again. I guess I'll close this one as it's probably not your problem. Cheers!

**Comment by mysterybear** [comment]
FWIW this seems to be an issue with Archlinux proaudio's packaging of VCV. The issue goes away if I use the zipped binary from the VCV website.
