### ISSUE TITLE
documentation for how to unhide looper2?

### ISSUE THREAD

**Issue by n9n9n9** [grough/lilac-loop-vcv#15]
I had been using it and carefully keeping it alive on my old computer, but cannot for the life of me get it working on my new one. I love looper2.. little help?

**Comment by grough** [comment]
Hey, sorry about that. I just noticed it was set to "hidden" in plugin.json.

You can download the latest (including looper 2) here:

https://grough.github.io/lilac-loop-vcv/latest/

**Comment by grough** [comment]
Just wanted to ping you @n9n9n9 to make sure you saw the link above before I close this issue.
