### ISSUE TITLE
[Feature request] feedback knob

### ISSUE THREAD

**Issue by jonulrich** [grough/lilac-loop-vcv#16]
I used to use ableton's looper quite a bit and one of the features that I used a fair bit was that it had a feedback knob so that you could let loops fade out while you overdub new loops and create constantly evolving loops.

It also wouldn't be necessary to add an entirely new knob (at least for my purposes), the mix knob as is basically of no use to me. I'm sure its useful for some though so I imagine maybe using an option in the right click menu, or a toggle button on the gui to switch between mix knob functions would be an alright move and easy to implement.

**Comment by grough** [comment]
Hi, the latest pre-release version includes a looper with a feedback control. You can download it here: https://grough.github.io/lilac-loop-vcv/latest/

Beware the extra features may not work perfectly. But the existing feature set is in working order.

<img width="475" alt="Screenshot 2023-06-23 at 7 02 28 PM" src="https://github.com/grough/lilac-loop-vcv/assets/214106/faf2d0b9-1e80-4c06-b824-9830f418b12b">

**Comment by jonulrich** [comment]
oops, was exclusively using cardinal so I skipped downloading the pre-release to see where development was at. I kind of figured that if there were big changes ahead it would be obviously written somewhere.
