### ISSUE TITLE
No polyphonic output yet...

### ISSUE THREAD

**Issue by vcvrackideas** [grough/lilac-loop-vcv#2]
Hi! THanks for fixing previous issue with Windows. However I can't get a poly output with connecting 8 channel (for example) poly cable into input of Lilac. Hope you can solve it, cheers!

**Comment by grough** [comment]
Here's a screenshot of my attempt to reproduce the problem on Windows. Polyphonic input and output appear to be working as expected. Here I am only using 3 channels of polyphony, though my deeper testing on macOS suggests that up to 16 channels should work just as well.

Maybe you are affected by this recently documented issue: "[Number of polyphonic channels is constant per recording](https://github.com/grough/lilac-loop-vcv/issues/3)". Is it possible that you began your test by recording a mono input, then added more inputs while working with the same loop? If you could try erasing and recording a brand new loop with multiple channels connected I would be interested to hear the results.

<img width="960" alt="VCV Rack Lilac Looper polyphony test" src="https://user-images.githubusercontent.com/214106/96024601-f447fc00-0e21-11eb-8d0c-2f735697f885.png">

**Comment by grough** [comment]
It's been a week with no new info, so I'll close this. Polyphony appears to be working as designed in Windows 10 (based on my own testing and reports from a few Windows users).
