### ISSUE TITLE
Can't seem to get the Looper to record

### ISSUE THREAD

**Issue by Kleinemaschinen** [grough/lilac-loop-vcv#4]
Hello there grough, 
I can't seem to get the looper to record in any of the 3 different patches, am I missing something?
I can show you a screenshot on VCV patch storage, if that would  help?
![Stereo eg-Lilac looper my set up](https://user-images.githubusercontent.com/73140555/96511541-2066e100-1257-11eb-9dfd-ab49b854f5df.JPG)

**Comment by grough** [comment]
Hi @Kleinemaschinen. Sorry to hear you're having trouble.

I see in your screenshot that "[No device]" is selected in the Audio-8 module below "ASIO". If you haven't already, could you try selecting a device and see if that makes a difference?

If that doesn't help, I'll take a closer look to make sure the example patches are working as expected on Windows. Maybe I missed something.

**Comment by grough** [comment]
Another question for you @Kleinemaschinen - do any of the Looper module's status lights light up when you try to record, or does it not respond at all?

**Comment by grough** [comment]
Closed due to inactivity
