### ISSUE TITLE
I managed to get one channel out of the Mono version

### ISSUE THREAD

**Issue by Kleinemaschinen** [grough/lilac-loop-vcv#5]
Thanks for looking into the issue, I managed to get 1 channel out of the mono version set up. 
Not tried the Stereo and poly version patches. I will give them another go. They do look promising , just got to get my head around their inner workings. 
Thanks Kleinemaschinen.

**Comment by grough** [comment]
Thanks for your reply. Glad to hear the mono version is working for you.
