### ISSUE TITLE
Missing Save on Context Menu

### ISSUE THREAD

**Issue by technochitlin** [grough/lilac-loop-vcv#8]
Just tried this tonight- but I can't seem to save my recorded loop- the context menu has no entries for either Overdub or Save File that are noted in the manual. Just getting the standard RackV1 context menu. Am I missing something?

**Comment by grough** [comment]
My mistake - I updated the manual page before I actually published the "Save" feature to the VCV Library. I'll hide that section of the manual until it's released. You can find a pre-release version of Lilac with the Save feature for Rack v1 here: https://github.com/grough/lilac-loop-vcv/releases/tag/v1.0.3.dev1

**Comment by technochitlin** [comment]
Thanks!
